server:
  port: 9001
  tomcat:
    uri-encoding: UTF-8  
spring:
  application:
    name: sc-ps-api 
       
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

#整合Spring Security实现访问API页面输入用户名密码 ,enabled:true为开启        
#security:
#  basic:
#    path: /swagger-ui.html
#    enabled: false
#  user:
#    name: lvjh
#    password: 123456